/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.1.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QWidget>
#include "clickablelabel.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionStart;
    QAction *actionForfeit;
    QAction *actionCreate_Connection;
    QAction *actionConnect_to_Server;
    QAction *actionDisconnect;
    QAction *actionRules;
    QAction *actionRefresh;
    QWidget *centralwidget;
    QLabel *background;
    QLabel *board;
    ClickableLabel *label_1;
    ClickableLabel *label_2;
    ClickableLabel *label_3;
    ClickableLabel *label_4;
    ClickableLabel *label_5;
    ClickableLabel *label_6;
    ClickableLabel *label_7;
    ClickableLabel *label_8;
    ClickableLabel *label_9;
    ClickableLabel *label_10;
    ClickableLabel *label_11;
    ClickableLabel *label_12;
    ClickableLabel *label_13;
    ClickableLabel *label_14;
    ClickableLabel *label_15;
    ClickableLabel *label_16;
    ClickableLabel *label_17;
    ClickableLabel *label_18;
    ClickableLabel *label_19;
    ClickableLabel *label_20;
    ClickableLabel *label_21;
    ClickableLabel *label_22;
    ClickableLabel *label_23;
    ClickableLabel *label_24;
    ClickableLabel *label_25;
    ClickableLabel *label_26;
    ClickableLabel *label_27;
    ClickableLabel *label_28;
    ClickableLabel *label_29;
    ClickableLabel *label_30;
    ClickableLabel *label_31;
    ClickableLabel *label_32;
    ClickableLabel *label_33;
    ClickableLabel *label_34;
    ClickableLabel *label_35;
    ClickableLabel *label_36;
    ClickableLabel *label_37;
    ClickableLabel *label_38;
    ClickableLabel *label_39;
    ClickableLabel *label_40;
    ClickableLabel *label_41;
    ClickableLabel *label_42;
    ClickableLabel *label_43;
    ClickableLabel *label_44;
    ClickableLabel *label_45;
    ClickableLabel *label_46;
    ClickableLabel *label_47;
    ClickableLabel *label_48;
    ClickableLabel *label_49;
    ClickableLabel *label_50;
    QLabel *timeremain;
    QLabel *countdown;
    ClickableLabel *label_51;
    ClickableLabel *label_52;
    ClickableLabel *label_53;
    ClickableLabel *label_54;
    ClickableLabel *label_55;
    ClickableLabel *label_56;
    ClickableLabel *label_57;
    ClickableLabel *label_58;
    ClickableLabel *label_59;
    ClickableLabel *label_60;
    QLabel *blue;
    QLabel *error;
    QLabel *selectimage;
    QLabel *select;
    QLabel *error_2;
    QLabel *turn;
    QLabel *red;
    QLabel *move;
    QLabel *count;
    QTextBrowser *tt1;
    QTextBrowser *tt2;
    QLabel *lives;
    QLabel *count_2;
    QMenuBar *menubar;
    QMenu *menuServer;
    QMenu *menuPlay;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->setWindowModality(Qt::NonModal);
        MainWindow->resize(500, 771);
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
        MainWindow->setSizePolicy(sizePolicy);
        MainWindow->setMinimumSize(QSize(500, 771));
        MainWindow->setMaximumSize(QSize(500, 771));
        MainWindow->setCursor(QCursor(Qt::PointingHandCursor));
        actionStart = new QAction(MainWindow);
        actionStart->setObjectName(QString::fromUtf8("actionStart"));
        actionForfeit = new QAction(MainWindow);
        actionForfeit->setObjectName(QString::fromUtf8("actionForfeit"));
        actionCreate_Connection = new QAction(MainWindow);
        actionCreate_Connection->setObjectName(QString::fromUtf8("actionCreate_Connection"));
        actionConnect_to_Server = new QAction(MainWindow);
        actionConnect_to_Server->setObjectName(QString::fromUtf8("actionConnect_to_Server"));
        actionDisconnect = new QAction(MainWindow);
        actionDisconnect->setObjectName(QString::fromUtf8("actionDisconnect"));
        actionRules = new QAction(MainWindow);
        actionRules->setObjectName(QString::fromUtf8("actionRules"));
        actionRefresh = new QAction(MainWindow);
        actionRefresh->setObjectName(QString::fromUtf8("actionRefresh"));
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        background = new QLabel(centralwidget);
        background->setObjectName(QString::fromUtf8("background"));
        background->setGeometry(QRect(0, 0, 661, 921));
        background->setPixmap(QPixmap(QString::fromUtf8(":/new/prefix1/background.png")));
        background->setScaledContents(false);
        background->setWordWrap(false);
        board = new QLabel(centralwidget);
        board->setObjectName(QString::fromUtf8("board"));
        board->setEnabled(true);
        board->setGeometry(QRect(30, 100, 451, 611));
        board->setPixmap(QPixmap(QString::fromUtf8(":/new/prefix1/board.png")));
        board->setScaledContents(true);
        board->setWordWrap(true);
        label_1 = new ClickableLabel(centralwidget);
        label_1->setObjectName(QString::fromUtf8("label_1"));
        label_1->setEnabled(true);
        label_1->setGeometry(QRect(30, 100, 71, 31));
        label_1->setScaledContents(true);
        label_2 = new ClickableLabel(centralwidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setEnabled(true);
        label_2->setGeometry(QRect(120, 100, 71, 31));
        label_2->setScaledContents(true);
        label_3 = new ClickableLabel(centralwidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setEnabled(true);
        label_3->setGeometry(QRect(220, 100, 71, 31));
        label_3->setScaledContents(true);
        label_4 = new ClickableLabel(centralwidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setEnabled(true);
        label_4->setGeometry(QRect(320, 100, 71, 31));
        label_4->setScaledContents(true);
        label_5 = new ClickableLabel(centralwidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setEnabled(true);
        label_5->setGeometry(QRect(410, 100, 71, 31));
        label_5->setScaledContents(true);
        label_6 = new ClickableLabel(centralwidget);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setEnabled(true);
        label_6->setGeometry(QRect(30, 142, 71, 31));
        label_6->setScaledContents(true);
        label_7 = new ClickableLabel(centralwidget);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setEnabled(true);
        label_7->setGeometry(QRect(120, 142, 71, 31));
        label_7->setScaledContents(true);
        label_8 = new ClickableLabel(centralwidget);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setEnabled(true);
        label_8->setGeometry(QRect(220, 142, 71, 31));
        label_8->setScaledContents(true);
        label_9 = new ClickableLabel(centralwidget);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setEnabled(true);
        label_9->setGeometry(QRect(320, 142, 71, 31));
        label_9->setScaledContents(true);
        label_10 = new ClickableLabel(centralwidget);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setEnabled(true);
        label_10->setGeometry(QRect(410, 142, 71, 31));
        label_10->setScaledContents(true);
        label_11 = new ClickableLabel(centralwidget);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setEnabled(true);
        label_11->setGeometry(QRect(30, 189, 71, 31));
        label_11->setScaledContents(true);
        label_12 = new ClickableLabel(centralwidget);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setEnabled(true);
        label_12->setGeometry(QRect(220, 189, 71, 31));
        label_12->setScaledContents(true);
        label_13 = new ClickableLabel(centralwidget);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setEnabled(true);
        label_13->setGeometry(QRect(410, 189, 71, 31));
        label_13->setScaledContents(true);
        label_14 = new ClickableLabel(centralwidget);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setEnabled(true);
        label_14->setGeometry(QRect(30, 232, 71, 31));
        label_14->setScaledContents(true);
        label_15 = new ClickableLabel(centralwidget);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setEnabled(true);
        label_15->setGeometry(QRect(120, 232, 71, 31));
        label_15->setScaledContents(true);
        label_16 = new ClickableLabel(centralwidget);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setEnabled(true);
        label_16->setGeometry(QRect(320, 232, 71, 31));
        label_16->setScaledContents(true);
        label_17 = new ClickableLabel(centralwidget);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setEnabled(true);
        label_17->setGeometry(QRect(410, 232, 71, 31));
        label_17->setScaledContents(true);
        label_18 = new ClickableLabel(centralwidget);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setEnabled(true);
        label_18->setGeometry(QRect(30, 277, 71, 31));
        label_18->setScaledContents(true);
        label_19 = new ClickableLabel(centralwidget);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setEnabled(true);
        label_19->setGeometry(QRect(220, 277, 71, 31));
        label_19->setScaledContents(true);
        label_20 = new ClickableLabel(centralwidget);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setEnabled(true);
        label_20->setGeometry(QRect(410, 277, 71, 31));
        label_20->setScaledContents(true);
        label_21 = new ClickableLabel(centralwidget);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setEnabled(true);
        label_21->setGeometry(QRect(30, 320, 71, 31));
        label_21->setScaledContents(true);
        label_22 = new ClickableLabel(centralwidget);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setEnabled(true);
        label_22->setGeometry(QRect(120, 320, 71, 31));
        label_22->setScaledContents(true);
        label_23 = new ClickableLabel(centralwidget);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setEnabled(true);
        label_23->setGeometry(QRect(220, 320, 71, 31));
        label_23->setScaledContents(true);
        label_24 = new ClickableLabel(centralwidget);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setEnabled(true);
        label_24->setGeometry(QRect(320, 320, 71, 31));
        label_24->setScaledContents(true);
        label_25 = new ClickableLabel(centralwidget);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setEnabled(true);
        label_25->setGeometry(QRect(410, 320, 71, 31));
        label_25->setScaledContents(true);
        label_26 = new ClickableLabel(centralwidget);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setEnabled(true);
        label_26->setGeometry(QRect(30, 680, 71, 31));
        label_26->setScaledContents(true);
        label_27 = new ClickableLabel(centralwidget);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setEnabled(true);
        label_27->setGeometry(QRect(120, 680, 71, 31));
        label_27->setScaledContents(true);
        label_28 = new ClickableLabel(centralwidget);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setEnabled(true);
        label_28->setGeometry(QRect(220, 680, 71, 31));
        label_28->setScaledContents(true);
        label_29 = new ClickableLabel(centralwidget);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setEnabled(true);
        label_29->setGeometry(QRect(320, 680, 71, 31));
        label_29->setScaledContents(true);
        label_30 = new ClickableLabel(centralwidget);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setEnabled(true);
        label_30->setGeometry(QRect(410, 680, 71, 31));
        label_30->setScaledContents(true);
        label_31 = new ClickableLabel(centralwidget);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setEnabled(true);
        label_31->setGeometry(QRect(30, 636, 71, 31));
        label_31->setScaledContents(true);
        label_32 = new ClickableLabel(centralwidget);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setEnabled(true);
        label_32->setGeometry(QRect(120, 636, 71, 31));
        label_32->setScaledContents(true);
        label_33 = new ClickableLabel(centralwidget);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setEnabled(true);
        label_33->setGeometry(QRect(220, 636, 71, 31));
        label_33->setScaledContents(true);
        label_34 = new ClickableLabel(centralwidget);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setEnabled(true);
        label_34->setGeometry(QRect(320, 636, 71, 31));
        label_34->setScaledContents(true);
        label_35 = new ClickableLabel(centralwidget);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setEnabled(true);
        label_35->setGeometry(QRect(410, 636, 71, 31));
        label_35->setScaledContents(true);
        label_36 = new ClickableLabel(centralwidget);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setEnabled(true);
        label_36->setGeometry(QRect(30, 590, 71, 31));
        label_36->setScaledContents(true);
        label_37 = new ClickableLabel(centralwidget);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setEnabled(true);
        label_37->setGeometry(QRect(220, 590, 71, 31));
        label_37->setScaledContents(true);
        label_38 = new ClickableLabel(centralwidget);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setEnabled(true);
        label_38->setGeometry(QRect(410, 590, 71, 31));
        label_38->setScaledContents(true);
        label_39 = new ClickableLabel(centralwidget);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setEnabled(true);
        label_39->setGeometry(QRect(30, 547, 71, 31));
        label_39->setScaledContents(true);
        label_40 = new ClickableLabel(centralwidget);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setEnabled(true);
        label_40->setGeometry(QRect(120, 547, 71, 31));
        label_40->setScaledContents(true);
        label_41 = new ClickableLabel(centralwidget);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setEnabled(true);
        label_41->setGeometry(QRect(320, 547, 71, 31));
        label_41->setScaledContents(true);
        label_42 = new ClickableLabel(centralwidget);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setEnabled(true);
        label_42->setGeometry(QRect(410, 547, 71, 31));
        label_42->setScaledContents(true);
        label_43 = new ClickableLabel(centralwidget);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setEnabled(true);
        label_43->setGeometry(QRect(30, 502, 71, 31));
        label_43->setScaledContents(true);
        label_44 = new ClickableLabel(centralwidget);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setEnabled(true);
        label_44->setGeometry(QRect(220, 502, 71, 31));
        label_44->setScaledContents(true);
        label_45 = new ClickableLabel(centralwidget);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setEnabled(true);
        label_45->setGeometry(QRect(410, 502, 71, 31));
        label_45->setScaledContents(true);
        label_46 = new ClickableLabel(centralwidget);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setEnabled(true);
        label_46->setGeometry(QRect(30, 460, 71, 31));
        label_46->setScaledContents(true);
        label_47 = new ClickableLabel(centralwidget);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setEnabled(true);
        label_47->setGeometry(QRect(120, 460, 71, 31));
        label_47->setScaledContents(true);
        label_48 = new ClickableLabel(centralwidget);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setEnabled(true);
        label_48->setGeometry(QRect(220, 460, 71, 31));
        label_48->setScaledContents(true);
        label_49 = new ClickableLabel(centralwidget);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setEnabled(true);
        label_49->setGeometry(QRect(320, 460, 71, 31));
        label_49->setScaledContents(true);
        label_50 = new ClickableLabel(centralwidget);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setEnabled(true);
        label_50->setGeometry(QRect(410, 460, 71, 31));
        label_50->setScaledContents(true);
        timeremain = new QLabel(centralwidget);
        timeremain->setObjectName(QString::fromUtf8("timeremain"));
        timeremain->setGeometry(QRect(30, 60, 161, 31));
        QFont font;
        font.setPointSize(12);
        font.setBold(true);
        font.setStyleStrategy(QFont::PreferAntialias);
        timeremain->setFont(font);
        timeremain->setScaledContents(false);
        countdown = new QLabel(centralwidget);
        countdown->setObjectName(QString::fromUtf8("countdown"));
        countdown->setGeometry(QRect(170, 60, 81, 31));
        QFont font1;
        font1.setPointSize(16);
        font1.setBold(true);
        countdown->setFont(font1);
        label_51 = new ClickableLabel(centralwidget);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setEnabled(true);
        label_51->setGeometry(QRect(120, 190, 71, 31));
        label_51->setScaledContents(true);
        label_52 = new ClickableLabel(centralwidget);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setEnabled(true);
        label_52->setGeometry(QRect(310, 190, 71, 31));
        label_52->setScaledContents(true);
        label_53 = new ClickableLabel(centralwidget);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setEnabled(true);
        label_53->setGeometry(QRect(220, 230, 71, 31));
        label_53->setScaledContents(true);
        label_54 = new ClickableLabel(centralwidget);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setEnabled(true);
        label_54->setGeometry(QRect(120, 270, 71, 31));
        label_54->setScaledContents(true);
        label_55 = new ClickableLabel(centralwidget);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setEnabled(true);
        label_55->setGeometry(QRect(310, 270, 71, 31));
        label_55->setScaledContents(true);
        label_56 = new ClickableLabel(centralwidget);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setEnabled(true);
        label_56->setGeometry(QRect(130, 590, 71, 31));
        label_56->setScaledContents(true);
        label_57 = new ClickableLabel(centralwidget);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setEnabled(true);
        label_57->setGeometry(QRect(320, 590, 71, 31));
        label_57->setScaledContents(true);
        label_58 = new ClickableLabel(centralwidget);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setEnabled(true);
        label_58->setGeometry(QRect(220, 550, 71, 31));
        label_58->setScaledContents(true);
        label_59 = new ClickableLabel(centralwidget);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setEnabled(true);
        label_59->setGeometry(QRect(130, 500, 71, 31));
        label_59->setScaledContents(true);
        label_60 = new ClickableLabel(centralwidget);
        label_60->setObjectName(QString::fromUtf8("label_60"));
        label_60->setEnabled(true);
        label_60->setGeometry(QRect(320, 500, 71, 31));
        label_60->setScaledContents(true);
        blue = new QLabel(centralwidget);
        blue->setObjectName(QString::fromUtf8("blue"));
        blue->setGeometry(QRect(30, 20, 81, 41));
        QFont font2;
        font2.setPointSize(25);
        font2.setBold(true);
        blue->setFont(font2);
        error = new QLabel(centralwidget);
        error->setObjectName(QString::fromUtf8("error"));
        error->setGeometry(QRect(84, 372, 151, 61));
        QFont font3;
        font3.setPointSize(20);
        font3.setBold(true);
        font3.setItalic(false);
        error->setFont(font3);
        error->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        selectimage = new QLabel(centralwidget);
        selectimage->setObjectName(QString::fromUtf8("selectimage"));
        selectimage->setGeometry(QRect(78, 390, 71, 31));
        selectimage->setScaledContents(true);
        select = new QLabel(centralwidget);
        select->setObjectName(QString::fromUtf8("select"));
        select->setGeometry(QRect(157, 380, 91, 51));
        QFont font4;
        font4.setPointSize(14);
        font4.setBold(true);
        select->setFont(font4);
        error_2 = new QLabel(centralwidget);
        error_2->setObjectName(QString::fromUtf8("error_2"));
        error_2->setGeometry(QRect(357, 8, 121, 71));
        error_2->setFont(font3);
        error_2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        turn = new QLabel(centralwidget);
        turn->setObjectName(QString::fromUtf8("turn"));
        turn->setGeometry(QRect(293, 363, 131, 51));
        QFont font5;
        font5.setPointSize(18);
        font5.setBold(true);
        turn->setFont(font5);
        red = new QLabel(centralwidget);
        red->setObjectName(QString::fromUtf8("red"));
        red->setEnabled(true);
        red->setGeometry(QRect(30, 20, 81, 41));
        red->setFont(font2);
        move = new QLabel(centralwidget);
        move->setObjectName(QString::fromUtf8("move"));
        move->setGeometry(QRect(303, 410, 61, 21));
        count = new QLabel(centralwidget);
        count->setObjectName(QString::fromUtf8("count"));
        count->setGeometry(QRect(368, 411, 21, 21));
        QFont font6;
        font6.setPointSize(10);
        font6.setBold(true);
        count->setFont(font6);
        tt1 = new QTextBrowser(centralwidget);
        tt1->setObjectName(QString::fromUtf8("tt1"));
        tt1->setGeometry(QRect(37, 0, 221, 111));
        tt1->setStyleSheet(QString::fromUtf8("background-color: rgba(0, 0, 0, 0);\n"
"border-color: rgba(0, 0, 0, 0);"));
        tt2 = new QTextBrowser(centralwidget);
        tt2->setObjectName(QString::fromUtf8("tt2"));
        tt2->setGeometry(QRect(267, 34, 211, 71));
        tt2->setStyleSheet(QString::fromUtf8("background-color: rgba(0, 0, 0, 0);\n"
"border-color: rgba(0, 0, 0, 0);"));
        lives = new QLabel(centralwidget);
        lives->setObjectName(QString::fromUtf8("lives"));
        lives->setGeometry(QRect(415, 78, 61, 21));
        count_2 = new QLabel(centralwidget);
        count_2->setObjectName(QString::fromUtf8("count_2"));
        count_2->setGeometry(QRect(458, 79, 21, 21));
        count_2->setFont(font6);
        MainWindow->setCentralWidget(centralwidget);
        background->raise();
        board->raise();
        label_1->raise();
        label_2->raise();
        label_3->raise();
        label_4->raise();
        label_5->raise();
        label_6->raise();
        label_7->raise();
        label_8->raise();
        label_9->raise();
        label_10->raise();
        label_11->raise();
        label_12->raise();
        label_13->raise();
        label_14->raise();
        label_15->raise();
        label_16->raise();
        label_17->raise();
        label_18->raise();
        label_19->raise();
        label_20->raise();
        label_21->raise();
        label_22->raise();
        label_23->raise();
        label_24->raise();
        label_25->raise();
        label_26->raise();
        label_27->raise();
        label_28->raise();
        label_29->raise();
        label_30->raise();
        label_31->raise();
        label_32->raise();
        label_33->raise();
        label_34->raise();
        label_35->raise();
        label_36->raise();
        label_37->raise();
        label_38->raise();
        label_39->raise();
        label_40->raise();
        label_41->raise();
        label_42->raise();
        label_43->raise();
        label_44->raise();
        label_45->raise();
        label_46->raise();
        label_47->raise();
        label_48->raise();
        label_49->raise();
        label_50->raise();
        timeremain->raise();
        countdown->raise();
        label_51->raise();
        label_52->raise();
        label_53->raise();
        label_54->raise();
        label_55->raise();
        label_56->raise();
        label_57->raise();
        label_58->raise();
        label_59->raise();
        label_60->raise();
        blue->raise();
        selectimage->raise();
        select->raise();
        error_2->raise();
        turn->raise();
        red->raise();
        error->raise();
        move->raise();
        count->raise();
        tt1->raise();
        tt2->raise();
        lives->raise();
        count_2->raise();
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 500, 21));
        menuServer = new QMenu(menubar);
        menuServer->setObjectName(QString::fromUtf8("menuServer"));
        menuPlay = new QMenu(menubar);
        menuPlay->setObjectName(QString::fromUtf8("menuPlay"));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        menubar->addAction(menuServer->menuAction());
        menubar->addAction(menuPlay->menuAction());
        menuServer->addSeparator();
        menuServer->addAction(actionCreate_Connection);
        menuServer->addAction(actionConnect_to_Server);
        menuServer->addAction(actionDisconnect);
        menuPlay->addSeparator();
        menuPlay->addAction(actionStart);
        menuPlay->addAction(actionForfeit);
        menuPlay->addAction(actionRefresh);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "JunQi", nullptr));
        actionStart->setText(QCoreApplication::translate("MainWindow", "Start", nullptr));
        actionForfeit->setText(QCoreApplication::translate("MainWindow", "Forfeit", nullptr));
        actionCreate_Connection->setText(QCoreApplication::translate("MainWindow", "Create Connection", nullptr));
        actionConnect_to_Server->setText(QCoreApplication::translate("MainWindow", "Connect to Server", nullptr));
        actionDisconnect->setText(QCoreApplication::translate("MainWindow", "Disconnect", nullptr));
        actionRules->setText(QCoreApplication::translate("MainWindow", "Rules", nullptr));
        actionRefresh->setText(QCoreApplication::translate("MainWindow", "Refresh", nullptr));
        background->setText(QString());
        board->setText(QString());
        label_1->setText(QString());
        label_2->setText(QString());
        label_3->setText(QString());
        label_4->setText(QString());
        label_5->setText(QString());
        label_6->setText(QString());
        label_7->setText(QString());
        label_8->setText(QString());
        label_9->setText(QString());
        label_10->setText(QString());
        label_11->setText(QString());
        label_12->setText(QString());
        label_13->setText(QString());
        label_14->setText(QString());
        label_15->setText(QString());
        label_16->setText(QString());
        label_17->setText(QString());
        label_18->setText(QString());
        label_19->setText(QString());
        label_20->setText(QString());
        label_21->setText(QString());
        label_22->setText(QString());
        label_23->setText(QString());
        label_24->setText(QString());
        label_25->setText(QString());
        label_26->setText(QString());
        label_27->setText(QString());
        label_28->setText(QString());
        label_29->setText(QString());
        label_30->setText(QString());
        label_31->setText(QString());
        label_32->setText(QString());
        label_33->setText(QString());
        label_34->setText(QString());
        label_35->setText(QString());
        label_36->setText(QString());
        label_37->setText(QString());
        label_38->setText(QString());
        label_39->setText(QString());
        label_40->setText(QString());
        label_41->setText(QString());
        label_42->setText(QString());
        label_43->setText(QString());
        label_44->setText(QString());
        label_45->setText(QString());
        label_46->setText(QString());
        label_47->setText(QString());
        label_48->setText(QString());
        label_49->setText(QString());
        label_50->setText(QString());
        timeremain->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Time Remaining:</span></p></body></html>", nullptr));
        countdown->setText(QString());
        label_51->setText(QString());
        label_52->setText(QString());
        label_53->setText(QString());
        label_54->setText(QString());
        label_55->setText(QString());
        label_56->setText(QString());
        label_57->setText(QString());
        label_58->setText(QString());
        label_59->setText(QString());
        label_60->setText(QString());
        blue->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aaff;\">Blue</span></p></body></html>", nullptr));
        error->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">Invalid Move!</span></p></body></html>", nullptr));
        selectimage->setText(QString());
        select->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Selected</span></p></body></html>", nullptr));
        error_2->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">Time Limit </span></p><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">Exceeded!!</span></p></body></html>", nullptr));
        turn->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Your Turn</span></p></body></html>", nullptr));
        red->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">Red</span></p></body></html>", nullptr));
        move->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">Moves:</span></p></body></html>", nullptr));
        count->setText(QString());
        tt1->setHtml(QCoreApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.1pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">How To Play:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:6pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">1.)</span><span style=\" font-size:9pt; color:#ffffff;\"> Click </span><spa"
                        "n style=\" font-size:9pt; font-weight:600; color:#ffffff;\">Connect</span><span style=\" font-size:9pt; color:#ffffff;\"> &gt; </span><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">Create Connection</span><span style=\" font-size:9pt; color:#ffffff;\"> to host a server.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">2.)</span><span style=\" font-size:9pt; color:#ffffff;\"> Click </span><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">Connect</span><span style=\" font-size:9pt; color:#ffffff;\"> &gt; </span><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">Connect to Server</span><span style=\" font-size:9pt; color:#ffffff;\"> to join a server.</span></p></body></html>", nullptr));
        tt2->setHtml(QCoreApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.1pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">3.) </span><span style=\" font-size:9pt; color:#ffffff;\">Either side click </span><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">Play</span><span style=\" font-size:9pt; color:#ffffff;\"> &gt; </span><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">Start</span><span style=\" font-size:9pt; color:#ffffff;\"> to begin the game.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">"
                        "<span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">4.) </span><span style=\" font-size:9pt; color:#ffffff;\">You can forfeit from 20 moves onwards via </span><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">Play</span><span style=\" font-size:9pt; color:#ffffff;\"> &gt; </span><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">Forfeit</span><span style=\" font-size:9pt; color:#ffffff;\">.</span></p></body></html>", nullptr));
        lives->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">Lives:</span></p></body></html>", nullptr));
        count_2->setText(QString());
        menuServer->setTitle(QCoreApplication::translate("MainWindow", "Connect", nullptr));
        menuPlay->setTitle(QCoreApplication::translate("MainWindow", "Play", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
